apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
        - name: rails-app
          image: ghcr.io/thr3a/rails-sample:11
          resources: {}
          ports:
            - containerPort: 3000
