apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: thr3a/myrails:latest
        resources: {}
        ports:
        - containerPort: 3000
