name: Github Action CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: GitOps Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build an image from Dockerfile
        run: |
          DOCKER_BUILDKIT=1 docker image build . -f docker/rails/Dockerfile --tag ghcr.io/${{ repository_owner }}/rails-sample:${{ github.run_number }}
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: rails-sample:${{ github.run_number }}
      # - name: Change Pod Name
      #   run: |
      #     echo -e "machine github.com\nlogin ${{ secrets.GITHUBUSER }}\npassword ${{ secrets.GITHUBTOKEN }}" > ~/.netrc
      #     git config --global user.email ${{ secrets.EMAIL }}
      #     git config --global user.name ${{ secrets.GITHUBUSER }}
      #     git clone https://github.com/${{ secrets.GITHUBUSER }}/config.git
      #     cd config/manifest
      #     yq e '.metadata.name = "gitops-deployment${{ github.run_number }}"' -i app.yaml
      #     git add app.yaml
      #     git commit -m ${{ github.run_number }} -a
      #     git push origin main
